/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    submissions: Submission;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Mensajes enviados desde el formulario de contacto del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  status: 'new' | 'read' | 'replied';
  name: string;
  email: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe la imagen en una frase. Lo leen los lectores de pantalla y los buscadores.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  layout?: (HeroBlock | AboutBlock | StatsBlock | WhatWeDoBlock | ServicesBlock | ListBlock | ContactBlock)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Cada salto de línea es un corte del titular. Dos líneas es lo ideal.
   */
  title: string;
  /**
   * Tiene que aparecer tal cual en el título. Se muestra en cursiva con un trazo de aurora debajo.
   */
  highlight?: string | null;
  subtitle?: string | null;
  cta?: {
    label?: string | null;
    /**
     * Ancla o ruta interna (#contacto, /servicios) o URL completa (https://…).
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Ancla o ruta interna (#contacto, /servicios) o URL completa (https://…).
     */
    href?: string | null;
  };
  /**
   * Paisaje horizontal con cielo arriba y la parte oscura abajo, donde va el texto. El punto de enfoque de la imagen decide el encuadre.
   */
  background?: (number | null) | Media;
  /**
   * La misma imagen de fondo, del mismo tamaño, con el cielo transparente (PNG o WebP). Con ella la aurora pasa por detrás de las montañas.
   */
  foreground?: (number | null) | Media;
  /**
   * Cortinas de luz en los colores de la marca, que se mueven lento sobre el cielo.
   */
  aurora?: boolean | null;
  /**
   * Se enlaza como #ancla. Si se deja vacío, se genera una automáticamente.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Sin imagen, el texto ocupa el ancho completo.
   */
  image?: (number | null) | Media;
  /**
   * Se enlaza como #ancla. Si se deja vacío, se genera una automáticamente.
   */
  anchor?: string | null;
  /**
   * El fondo oscuro es un recurso de énfasis: una o dos secciones en toda la página. Si se usa en todas, deja de destacar ninguna.
   */
  surface?: ('primary' | 'anchor') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Línea corta sobre el título, en mayúsculas: «Salud mental y trabajo».
   */
  eyebrow?: string | null;
  title?: string | null;
  /**
   * Se muestra junto al título: «Fuente: OMS y OIT, 2022».
   */
  source?: string | null;
  /**
   * Cada tarjeta se lee como una frase: lo que va antes, la cifra y lo que significa.
   */
  items?:
    | {
        /**
         * Lo que abre la frase: «En el mundo», «Más de».
         */
        lead?: string | null;
        /**
         * Corta y contundente: «1 de cada 8», «US$ 1 billón».
         */
        value: string;
        /**
         * La parte de la cifra que se destaca: «1», «1 billón».
         */
        highlight?: string | null;
        accent?: ('boreas' | 'verde' | 'teal') | null;
        /**
         * Continúa la frase después de la cifra, en minúscula: «personas vive con…».
         */
        label: string;
        visual?: ('none' | 'people' | 'yearCost') | null;
        /**
         * El contador reparte este monto en el año y muestra lo acumulado hasta hoy. Un billón es 1000000000000.
         */
        annualAmount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Se enlaza como #ancla. Si se deja vacío, se genera una automáticamente.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatWeDoBlock".
 */
export interface WhatWeDoBlock {
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Se enlaza como #ancla. Si se deja vacío, se genera una automáticamente.
   */
  anchor?: string | null;
  /**
   * El fondo oscuro es un recurso de énfasis: una o dos secciones en toda la página. Si se usa en todas, deja de destacar ninguna.
   */
  surface?: ('primary' | 'anchor') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whatWeDo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  title: string;
  items?:
    | {
        /**
         * Idealmente un SVG o PNG cuadrado, con fondo transparente.
         */
        icon?: (number | null) | Media;
        title: string;
        description: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Se enlaza como #ancla. Si se deja vacío, se genera una automáticamente.
   */
  anchor?: string | null;
  /**
   * El fondo oscuro es un recurso de énfasis: una o dos secciones en toda la página. Si se usa en todas, deja de destacar ninguna.
   */
  surface?: ('primary' | 'anchor') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListBlock".
 */
export interface ListBlock {
  /**
   * Para enumeraciones cortas. Si cada ítem necesita una descripción, el bloque adecuado es Servicios.
   */
  title: string;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Se enlaza como #ancla. Si se deja vacío, se genera una automáticamente.
   */
  anchor?: string | null;
  /**
   * El fondo oscuro es un recurso de énfasis: una o dos secciones en toda la página. Si se usa en todas, deja de destacar ninguna.
   */
  surface?: ('primary' | 'anchor') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'list';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  /**
   * El email, el teléfono y la dirección se editan en Ajustes del sitio, no acá: así se actualizan en un solo lugar.
   */
  title: string;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Los mensajes recibidos aparecen en Contenido → Mensajes.
   */
  showForm?: boolean | null;
  /**
   * Se enlaza como #ancla. Si se deja vacío, se genera una automáticamente.
   */
  anchor?: string | null;
  /**
   * El fondo oscuro es un recurso de énfasis: una o dos secciones en toda la página. Si se usa en todas, deja de destacar ninguna.
   */
  surface?: ('primary' | 'anchor') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    /**
     * Se usa como texto alternativo y en el título del sitio.
     */
    name: string;
    /**
     * Se usa en el encabezado, el menú móvil y el pie. Idealmente SVG o PNG transparente.
     */
    logo?: (number | null) | Media;
    /**
     * Versión en blanco para el encabezado sobre la foto del hero. Si falta, se aclara el logo principal.
     */
    logoLight?: (number | null) | Media;
    /**
     * Frase corta que acompaña la marca en el pie.
     */
    tagline?: string | null;
  };
  /**
   * El destino es el ancla de una sección (#servicios) o una URL completa. El ancla de cada sección se define en el bloque correspondiente.
   */
  nav?:
    | {
        label: string;
        href: string;
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  contact: {
    email: string;
    phone?: string | null;
    address?: string | null;
  };
  footer?: {
    /**
     * El año se agrega automáticamente al renderizar.
     */
    copyright?: string | null;
  };
  socials?:
    | {
        platform: 'instagram' | 'linkedin' | 'facebook' | 'x' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Hasta unos 60 caracteres. Si se deja vacío, usa el nombre de la marca.
     */
    title?: string | null;
    /**
     * Entre 120 y 160 caracteres es lo que muestran los buscadores.
     */
    description?: string | null;
    /**
     * Proporción 1200 × 630 px.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        whatWeDo?: T | WhatWeDoBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        list?: T | ListBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  highlight?: T;
  subtitle?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  background?: T;
  foreground?: T;
  aurora?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  image?: T;
  anchor?: T;
  surface?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  source?: T;
  items?:
    | T
    | {
        lead?: T;
        value?: T;
        highlight?: T;
        accent?: T;
        label?: T;
        visual?: T;
        annualAmount?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatWeDoBlock_select".
 */
export interface WhatWeDoBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  anchor?: T;
  surface?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  anchor?: T;
  surface?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListBlock_select".
 */
export interface ListBlockSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  anchor?: T;
  surface?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  showForm?: T;
  anchor?: T;
  surface?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        logo?: T;
        logoLight?: T;
        tagline?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        highlight?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  footer?:
    | T
    | {
        copyright?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}